### ISSUE TITLE
Remove Links from Past Days in Calendar View

### ISSUE THREAD

**Issue by ak5** [wpic/flask-appointment-calendar#17]
You should not be able to select a day in the past.

**Comment by xiaohanyu** [comment]
Please check this? https://github.com/wpic/flask-appointment-calendar/commit/421ec52746e638e9fb85769b0f8fa7da00ca9c73

**Comment by ak5** [comment]
hi, I mean that the link to the url http://wpicmeet.com/appointment/create?date=2014-01-07 should not be linked to from the main page if current date is after 2014-01-07

**Comment by xiaohanyu** [comment]
Oh, I see. You just want to disable all the links before current date. OK.
