### ISSUE TITLE
JS time range slider implementation

### ISSUE THREAD

**Issue by xiaohanyu** [wpic/flask-appointment-calendar#7]
This project needs a js time range slider. 

http://marcneuwirth.com/blog/2010/02/21/using-a-jquery-ui-slider-to-select-a-time-range/ provide a simple one. We want additional features based on that:
1. The slider should have "taken time" and "free time", for "taken time", it may render that time range with red color, while for "free time", green.
2. We can not slide into the "taken time" ranger, this may require a simple initialization api like `Slider.init(taken_time_array)` and some frontend quicks to forbid sliding into the "taken time".

---

Updated requirements for this js widget:
1. ~~Need to support available time and unavailable time(rendered as red and green).~~
2. ~~When user's selection contains unavailable time range, disable all submit button.~~
3. ~~Should support timezone. When timezone changes, reload the widget. Need Ajax.~~ Moved to #13 
4. ~~Need a proper api.~~
5. ~~Use 24-hour format by default.~~
6. ~~Should compatible with bootstrap theme~~
7. ~~Need a special customized wtforms field for backend~~

**Comment by wendyshijia** [comment]
#1. given a taken time array, we could draw some red bars over a long green bar (or the other way round) with some js calculations; we could either draw html divs or use canvas

#2. it might be a bit unfriendly if we forbid user to drag handle into taken time period, as there is situation that user needs to drag a handle through a 'taken time'.

imagine the default two handles [+] are as follows:
 |-------green----[+]--------[+]------||------------red------------||----------green-----------|

the user should drag both handles through the red bar, to select a range in the second green bar as this:
 |-------green-------------------------||------------red------------||-----[+]--green---[+]----|

It would make sense if a warning pops up (and disable the 'next step' button, if any) when either handle is in the red bar

**Comment by xiaohanyu** [comment]
Hi, @wendyshijia 

Thanks for your reply. I've also considered the red period forbidden problem. I've got an idea. Could we implement an effect that do not forbid dragging into the red period, but instead, just drag over that period? Is it easy to implement this with js?

Thanks.

**Comment by wendyshijia** [comment]
what do you mean by 'drag over' ? if you mean both handle and mouse cursor
automatically move into the next green area, it feels jumpy, and i dont
think js could control mouse cursor.

if its possible, I'd like to have an idea of the situation this time slider
is used.

**Comment by xiaohanyu** [comment]
OK, I see. 

So we just use popup tips to remind users that the red area is not available time. And when user submit form, we use js to validate the time. How about this idea?

**Comment by xiaohanyu** [comment]
I've finished a basic implementation:

![image](https://f.cloud.github.com/assets/1164623/1962344/05f9ff4a-8286-11e3-8a41-a1191920b3ae.png)

**Comment by xiaohanyu** [comment]
Updated requirement for this js widget:
1. Need to support available time and forbidden time(render as red and green), almost finished.
2. ~~When users select forbidden time, disable all submit button.~~
3. Should add support for timezone. When timezone changes, reload the widget. 
4. Need a proper api.

**Comment by xiaohanyu** [comment]
The whole UI looks like this now:

![image](https://f.cloud.github.com/assets/1164623/1971225/b147978e-8323-11e3-959d-f2c05347c118.png)
